version: "3"

services:
  db:
    image: postgres:10-alpine
    ports:
      - ${DB_PORT:-5480}:5432
    environment:
      - POSTGRES_DB=${DB_NAME:-wb}
      - POSTGRES_USER=${DB_USER:-dev}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-pass}
