version: '3'

services:
  db:
    image: postgres:10-alpine
    ports:
      - ${DB_PORT:-5480}:5432
    environment:
      - POSTGRES_DB=${DB_NAME:-test}
      - POSTGRES_USER=${DB_USER:-test}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-pass}
